# Site settings
title: Produktionsbüro Lisa Gehring
email: mail@lisagehring.de
url: http://lisagehring.de
description: "Professionelle Produktionsleitung, Projektmanagement und Beratung für freie Künstler*innen mit Sitz in Frankfurt am Main"
keywords: "Produktionsleitung, Freie Darstellende Künste, Freie Kunst, Projektmanagement, Abrechnung, Antragstellung, Projektleitung, Theater, Kulturprojekte, Frankfurt"
meta_author: Lisa Gehring

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

color:
  primary: BA4D4D
  primary-rgb: "186,77,77"
  secondary: 9BC9EC
  tertiary: F0E691
  quaternary: 1F1F1F

# Footer settings
footer:
  copyright: Lisa Gehring
  location: Impressum
  social: Around the Web
  credits: Credits

# NICHT LÖSCHEN!
contact: static

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Lisa Gehring
  - line: Basaltstr. 9
  - line: 60487 Frankfurt am Main
  - line: <a href="mailto:mail@lisagehring.de">mail@lisagehring.de</a>

# Build settings
markdown: kramdown
permalink: pretty
